### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'singleShot'

### ISSUE THREAD

**Issue by cfgobel** [anitagraser/TimeManager#167]
Good Morning,
I got a Python error related to time manager plugin. I just got this error after updating to 2.14.3 on ubuntu 14.04. In reality I first got another error due zonalstatisticplugin, then I uninstalled QGIS (sudo apt-get purge QGIS) and reinstalled it. Does anybody else get this error? Thank.

The log message Traceback:
> Traceback (most recent call last):
> 			  File "/home/gobel/.qgis2/python/plugins/timemanager/timemanagercontrol.py", line 296, in waitAfterRenderComplete
> 			    QTimer.singleShot(self.animationFrameLength, self.playAnimation)
> 			AttributeError: 'NoneType' object has no attribute 'singleShot'

And the Stacktrace:

> An error has occurred while executing Python code:
> 
> AttributeError: 'NoneType' object has no attribute 'singleShot' 
> Traceback (most recent call last):
> File "/home/gobel/.qgis2/python/plugins/timemanager/timemanagercontrol.py", line 296, in waitAfterRenderComplete
> QTimer.singleShot(self.animationFrameLength, self.playAnimation)
> AttributeError: 'NoneType' object has no attribute 'singleShot'
> 
> Python version: 2.7.6 (default, Jun 22 2015, 18:01:27) [GCC 4.8.2] 
> QGIS version: 2.14.3-Essen Essen, exported
> 
> Python Path:
> /usr/share/qgis/python/plugins/processing
> /home/gobel/.qgis2/python/plugins/processinglwgeomprovider
> /usr/share/qgis/python
> /home/gobel/.qgis2/python
> /home/gobel/.qgis2/python/plugins
> /usr/share/qgis/python/plugins
> /usr/lib/python2.7
> /usr/lib/python2.7/plat-x86_64-linux-gnu
> /usr/lib/python2.7/lib-tk
> /usr/lib/python2.7/lib-old
> /usr/lib/python2.7/lib-dynload
> /usr/local/lib/python2.7/dist-packages
> /usr/lib/python2.7/dist-packages
> /usr/lib/python2.7/dist-packages/PILcompat
> /usr/lib/python2.7/dist-packages/gtk-2.0
> /usr/lib/pymodules/python2.7
> /usr/lib/python2.7/dist-packages/ubuntu-sso-client
> /usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode
> /home/gobel/.qgis2//python
> /home/gobel/.qgis2/python/plugins/DigitizingTools/tools
> /home/gobel/.qgis2/python/plugins/mmqgis/forms
> /home/gobel/.qgis2/python/plugins/DsgTools
> .
> /usr/share/qgis/python/plugins/fTools/tools
> /home/gobel/Data/Quantarctica2

**Comment by carolinux** [comment]
If you search here for 'QTimer' you will see that it's a somewhat random error. Re-installing may fix it.
https://anitagraser.com/projects/time-manager/

Now, those random errors usually have to do with C-to-Python conversions as is the case of the qt bindings, so I do have an idea of something to try that would fix the error, it's just hard to test since I can't reproduce it.

**Comment by carolinux** [comment]
a true mandelbug, thanks for updating

http://www.catb.org/jargon/html/M/mandelbug.html

**Comment by carolinux** [comment]
Re-opening this, to have it as a reminder to create an actual member object (ie self.timer) so that there's no object creation weirdness which is the most likely cause of this elusive bug.

**Comment by carolinux** [comment]
probably fixed now
