### ISSUE TITLE
QGIS crashes after updating TimeManager

### ISSUE THREAD

**Issue by oskarmule** [anitagraser/TimeManager#98]
After updating the Timemanager plugin today, qgis 2.6.1 chrashed. Qgis allso chrashes when I try to open Qgis. So I had to delete the plugin manualy, so I was able to open Qgis Again.
Error:
Kunne ikke indlæse plugin timemanager pga. en fejl ved kald af dens initGui()-metode

Traceback (most recent call last):
  File "C:/PROGRA~1/QGISBR~1/apps/qgis/./python\qgis\utils.py", line 217, in startPlugin
    plugins[packageName].initGui()
  File "C:/Users/osmule/.qgis2/python/plugins\timemanager\timemanager.py", line 59, in initGui
    control.load()
  File "C:/Users/osmule/.qgis2/python/plugins\timemanager\timemanagercontrol.py", line 32, in load
    self.initQGISConnections()
  File "C:/Users/osmule/.qgis2/python/plugins\timemanager\timemanagercontrol.py", line 57, in initQGISConnections
    QgsProject.instance().writeMapLayer.connect(self.writeSettings)
TypeError: connect() failed between writeMapLayer(QgsMapLayer*,QDomElement,QDomDocument) and unislot()

Python-version:
2.7.4 (default, Apr  6 2013, 19:54:46) [MSC v.1500 32 bit (Intel)]

QGIS-version:
2.6.1-Brighton Brighton, e2a51df
Kind regards Oskar

**Comment by carolinux** [comment]
I can't reproduce this fully on my ubuntu or Windows. It crashed when I updated the plugin, but I can subsequently use QGIS properly. Probably related to #95 and the memory issues here: http://enki-editor.org/2014/08/23/Pyqt_mem_mgmt.html
Will experiment with the old style slots in Qt and let you know.

**Comment by carolinux** [comment]
This is probably related also:
http://hub.qgis.org/issues/6573
So yeah, I will try old style slots and have a patch for you.

**Comment by carolinux** [comment]
Can you try using the github plugin (commit hash e16b750)
If this solves your problem we're going to release v 1.5.1 with it :)

**Comment by oskarmule** [comment]
Hi corolinux
It's running on Windows 7. 
I'm sorry, but i don't know how to do, what you are asking me to do. How can I run the curretn master  (commit hash e16b750)?

**Comment by carolinux** [comment]
@anitagraser  can we release v 1.5.1 with the current master for oskarmule?

**Comment by oskarmule** [comment]
Hi carolinux
I copy pasted the code you refered to insted of the "old" timemanagercontrol.py, and now qgis is working agin with Timemanager running.
By the way - excellent plugin :-)

**Comment by carolinux** [comment]
great that it worked, and thanks for the kind words. 
All the more reason to release 1.5.1 so that more Windows users can use the plugin bug-free.

**Comment by anitagraser** [comment]
I'm on it now

**Comment by anitagraser** [comment]
I just updated to 2.2 and crashed QGIS 2.13 ... (confirmed on Win8 and Debian)

**Comment by carolinux** [comment]
but does it work after you restart?

**Comment by carolinux** [comment]
yeah so this is *again* the same thing - something goes wrong with registering/unregistering the animation_datetime function. So it's more related to https://github.com/anitagraser/TimeManager/issues/95 than this issue

**Comment by cfgobel** [comment]
Good Morning,
I just got this error after updating to 2.14.3 on ubuntu 14.04:

> An error has occurred while executing Python code: 
> 
> AttributeError: 'NoneType' object has no attribute 'singleShot' 
> Traceback (most recent call last):
>   File "/home/gobel/.qgis2/python/plugins/timemanager/timemanagercontrol.py", line 296, in waitAfterRenderComplete
>     QTimer.singleShot(self.animationFrameLength, self.playAnimation)
> AttributeError: 'NoneType' object has no attribute 'singleShot'
> 
> 
> Python version: 2.7.6 (default, Jun 22 2015, 18:01:27) [GCC 4.8.2] 
> QGIS version: 2.14.3-Essen Essen, exported 
> 
> Python Path:
> /usr/share/qgis/python/plugins/processing
> /home/gobel/.qgis2/python/plugins/processinglwgeomprovider
> /usr/share/qgis/python
> /home/gobel/.qgis2/python
> /home/gobel/.qgis2/python/plugins
> /usr/share/qgis/python/plugins
> /usr/lib/python2.7
> /usr/lib/python2.7/plat-x86_64-linux-gnu
> /usr/lib/python2.7/lib-tk
> /usr/lib/python2.7/lib-old
> /usr/lib/python2.7/lib-dynload
> /usr/local/lib/python2.7/dist-packages
> /usr/lib/python2.7/dist-packages
> /usr/lib/python2.7/dist-packages/PILcompat
> /usr/lib/python2.7/dist-packages/gtk-2.0
> /usr/lib/pymodules/python2.7
> /usr/lib/python2.7/dist-packages/ubuntu-sso-client
> /usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode
> /home/gobel/.qgis2//python
> /home/gobel/.qgis2/python/plugins/DigitizingTools/tools
> /home/gobel/.qgis2/python/plugins/mmqgis/forms
> /home/gobel/.qgis2/python/plugins/DsgTools
> .
> /usr/share/qgis/python/plugins/fTools/tools
> /home/gobel/Data/Quantarctica2

**Comment by carolinux** [comment]
@cfgobel can you please create a new issue? this problem is unrelated to the ones discussed here...
